# Generated by Django 4.2.14 on 2024-08-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='id_read',
            new_name='is_read',
        ),
    ]
