# Generated by Django 4.2.14 on 2024-08-16 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_rename_id_read_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('newfriendrequest', 'New Friendrequest'), ('acceptedfriendrequest', 'Accepted Friendrequest'), ('rejectedfriendrequest', 'Rejected Friendrequest'), ('postlike', 'Post Like'), ('postcomment', 'Post Comment')], max_length=50),
        ),
    ]
