# Generated by Django 4.2.14 on 2024-08-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_friends_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('accapted', 'Accepted'), ('sent', 'Sent')], default='sent', max_length=20),
        ),
    ]
