# Generated by Django 4.2.14 on 2024-08-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_friendshiprequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('accapted', 'Accepted'), ('sent', 'Sent'), ('rejected', 'Rejected')], default='sent', max_length=20),
        ),
    ]
