# Generated by Django 4.2.14 on 2024-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_friendshiprequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('accapted', 'Accepted'), ('rejected', 'Rejected')], default='sent', max_length=20),
        ),
    ]
