# Generated by Django 4.2.14 on 2024-08-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_comments_count_comment_post_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
    ]
