# Generated by Django 4.2.14 on 2024-08-21 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_post_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reported_by_users',
            field=models.ManyToManyField(related_name='reported_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
